<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <RootNamespace>Cryptic_Transmitter</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\CT Logo B.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="CrypticIconF.ico" />
    <None Remove="Images\bg.jpg" />
    <None Remove="Images\bgpanel.png" />
    <None Remove="Images\CT Logo B.png" />
    <None Remove="Images\CT Logo S.png" />
    <None Remove="Images\default.png" />
    <None Remove="Images\discord.png" />
    <None Remove="Images\discordbtn.png" />
    <None Remove="Images\discordbtnh.png" />
    <None Remove="Images\discordhighlighted.png" />
    <None Remove="Images\Discord_H.png" />
    <None Remove="Images\GeneralButton.png" />
    <None Remove="Images\GeneralButtonD.png" />
    <None Remove="Images\GeneralButtonDisabled.png" />
    <None Remove="Images\GeneralButtonH.png" />
    <None Remove="Images\GeneralButton_H.png" />
    <None Remove="Images\Github.png" />
    <None Remove="Images\Github_H.png" />
    <None Remove="Images\HelpButtonD.png" />
    <None Remove="Images\HelpButtonH.png" />
    <None Remove="Images\IconSmall.png" />
    <None Remove="Images\Invisible.png" />
    <None Remove="Images\key-icon.png" />
    <None Remove="Images\lines.png" />
    <None Remove="Images\ListeningStarted.gif" />
    <None Remove="Images\ListeningStopped.png" />
    <None Remove="Images\logo.png" />
    <None Remove="Images\logo_e.png" />
    <None Remove="Images\offline.png" />
    <None Remove="Images\online.png" />
    <None Remove="Images\Panel.png" />
    <None Remove="Images\PanelDisabled.png" />
    <None Remove="Images\patreonbtn.png" />
    <None Remove="Images\patreonbtnh.png" />
    <None Remove="Images\Question.png" />
    <None Remove="Images\serverwaiting.gif" />
    <None Remove="Images\StartedD.png" />
    <None Remove="Images\StartedH.png" />
    <None Remove="Images\StoppedD.png" />
    <None Remove="Images\StoppedH.png" />
    <None Remove="Images\user-icon.png" />
    <None Remove="Images\Visible.png" />
    <None Remove="Images\Website.png" />
    <None Remove="Images\Website_H.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\CT Logo B.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" Version="24.4.0" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="CrypticIconF.ico" />
    <Resource Include="Images\bg.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\bgpanel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CT Logo B.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\CT Logo S.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\default.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\discord.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\discordbtn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\discordbtnh.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Discord_H.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\GeneralButton.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\GeneralButtonDisabled.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\GeneralButtonH.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\GeneralButtonD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\GeneralButton_H.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Github.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Github_H.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\HelpButtonD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\HelpButtonH.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\IconSmall.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Invisible.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\key-icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\lines.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ListeningStarted.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\ListeningStopped.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\offline.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\online.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Panel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\PanelDisabled.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\patreonbtn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\patreonbtnh.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Question.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\serverwaiting.gif">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\StartedD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\StartedH.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\StoppedD.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\StoppedH.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\user-icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Visible.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Website.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Website_H.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
